git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  edit: 'nvim -- {{filename}}'
  editAtLine: 'nvim +{{line}} -- {{filename}}'
  editAtLineAndWait: 'nvim +{{line}} -- {{filename}}'
  editInTerminal: true
