import = ["~/.config/alacritty/rose-pine/rose-pine.toml"]

[env]
TERM = 'xterm-256color'

[cursor.style]
blinking = "On"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[shell]
program = "/bin/zsh"
args = ["-l"] 
# "-c", "tmux attach || tmux new-session -s default"]

[window]
decorations = "Buttonless"
opacity = 1
option_as_alt = "OnlyLeft"

[window.padding]
x = 5
y = 5
